# Generated by Django 4.2.7 on 2024-01-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_category'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesModel',
            new_name='Categories',
        ),
    ]
