# Generated by Django 4.2.7 on 2024-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('availability_status', models.BooleanField(default=True)),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(default='', upload_to='catalog/media/uploads')),
            ],
        ),
    ]
